---

- name: Confirm deletion
  pause:
    prompt: "Is device {{ old_device_address.target.address }} unreachable? Are you sure you want to delete tenant {{ tenant_to_migrate }} and all its content on BIG-IQ only? (yes/no)"
  register: confirm_delete

# Force Delete ALL apps within tenant_to_migrate (old tenant)
- name: Force-Delete App services in case device in not reachable
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/tasks/force-delete"
    method: POST
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    body: |
      {
          "configSetName": "{{ item2 }}"
      }
    body_format: json
    status_code: 202
  register: json_response
  when: confirm_delete.user_input | bool

- name: Check Force-Delete status
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/tasks/force-delete/{{ json_response.json.id }}"
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: status
  until: status.json.status in ['FINISHED', 'FAILED']
  retries: 40
  delay: 10
  failed_when: "'FAILED' in status.json.status"
  changed_when: "'FINISHED' in status.json.status"
  when: confirm_delete.user_input | bool

- name: Cleanup Empty BIG-IQ Application in Dashboard
  include_tasks: "cleanup-bigiq-apps-dashboard.yaml"
  when: confirm_delete.user_input | bool