---
- name: Get old_device_address used by {{ tenant_to_migrate }}
  include_vars:
    file: "{{ dir_as3 }}/{{ tenant_to_migrate }}.json"
    name: old_device_address

- name: Confirm important deletion
  pause:
    prompt: "Are you sure you want to delete tenant {{ tenant_to_migrate }} and all its content from {{ old_device_address.target.address }}? (yes/no)"
  register: confirm_delete

# Delete old app service if remove_old_app true
- name: ATC POST - delete {{ tenant_to_migrate }}
  include_role:
    name: f5devcentral.atc_deploy
  vars:
    atc_service: AS3
    atc_method: POST
    atc_declaration: |
          {
              "class": "AS3",
              "action": "deploy",
              "persist": true,
              "declaration": {
                  "class": "ADC",
                  "schemaVersion": "3.7.0",
                  "id": "delete",
                  "label": "delete",
                  "remark": "delete",
                  "target": {
                      "address": "{{ old_device_address.target.address }}"
                  },
                  "{{ tenant_to_migrate }}": {
                      "class": "Tenant"
                  }
              }
          }
    atc_delay: 15
    atc_retries: 30
  register: atc_AS3_status
  when: confirm_delete.user_input | bool

# Delete old Global Apps which are empty in BIG-IQ Dashboard
- name: Retreive all BIG-IQ (global) Apps
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/global-apps
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: json_response
  when: confirm_delete.user_input | bool

- name: Get Empty Global App ID
  set_fact:
    global_app_id: "{{ json_response| json_query(query1) | flatten | json_query(query2) }}"
  vars: 
    query1: "json.items[?name != 'Unknown Applications']"
    query2: "[?appComponents == nul].id"
  when: confirm_delete.user_input | bool

- name: Delete empty global app
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/global-apps/{{ item }}"
    method: DELETE
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: application/json
      X-F5-Auth-Token: "{{ f5_auth_token }}"
  register: json_response
  with_items: "{{ global_app_id }}"
  when: confirm_delete.user_input | bool