---
# for cleanup-apps.yaml
- name: Get old_device_address used by {{ tenant_to_migrate }}
  include_vars:
    file: "{{ dir_as3 }}/{{ tenant_to_migrate }}.json"
    name: old_device_address

# for cleanup-apps-unreachable.yaml
- name: Get new tenant info
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/tenants?$filter=name%20eq%20'{{ tenant_to_migrate }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: json_response

- name: Get old tenant selfLink in old_tenant_selfLink
  set_fact:
    old_tenant_selfLink: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[0].selfLink"

- name: Get all configSetName old_tenant_selfLink
  uri:
    url: https://{{ provider.server }}:{{ provider.server_port }}/mgmt/cm/global/config-sets?$filter=tenantReference.link%20eq%20'{{ old_tenant_selfLink }}'
    method: GET
    timeout: "{{ timeout }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    status_code: 200, 202
  register: json_response

- name: Get configSetName in {{ tenant_to_migrate }}
  set_fact:
    configSetNames: "{{ json_response | json_query(query) }}"
  vars: 
    query: "json.items[*].configSetName"

- name: Application Services which will be deleted
  debug:
    msg: "{{ configSetNames }}"

